
###
GET http://localhost:3000

###
GET http://localhost:3000/geotags

###
POST http://localhost:3000/geotags
Content-Type: application/json

{
  "lat": 49,
  "long": 8,
  "nam": "green",
  "hash": "#h"
}






###
PUT http://localhost:3000/geotags/0 HTTP/1.1
Content-Type: application/json

{
	"lat": 43,
	"long": 40,
	"nam": "meh",
	"hash": "#home"
}

###
DELETE http://localhost:3000/1

###
GET http://localhost:3000/geotags/0
