
###
GET http://localhost:3000

###
GET http://localhost:3000/geotags

###
POST http://localhost:3000/geotags
Content-Type: application/json

{
  "lat": 49,
  "long": 8,
  "nam": "green",
  "hash": "#h"
}

###
POST http://localhost:3000/geotags
Content-Type: application/json

{
  "lat": 48,
  "long": 8,
  "nam": "POSTed",
  "hash": "#home"
}

###
GET http://localhost:3000/geotags/0



###
PUT http://localhost:3000/geotags/3
Content-Type: application/json

{
	"lat": 43,
	"long": 40,
	"nam": "PUTed-2",
	"hash": "#home"
}

###
DELETE http://localhost:3000/geotags/2

